// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromotionsCRM.Data;

#nullable disable

namespace PromotionsCRM.Migrations
{
    [DbContext(typeof(PromotionsCrmDbContext))]
    [Migration("20261006120917_insertdataforproductsandcountries")]
    partial class insertdataforproductsandcountries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PromotionsCRM.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Canon Street",
                            CountryId = 1,
                            Email = "canon@example.com",
                            Name = "Canon",
                            PhoneNumber = "123-456-7890",
                            RegisteredOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Website = "www.canon.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Nikon Avenue",
                            CountryId = 1,
                            Email = "nikon@example.com",
                            Name = "Nikon",
                            PhoneNumber = "987-654-3210",
                            RegisteredOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Website = "www.nikon.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Sony Boulevard",
                            CountryId = 1,
                            Email = "sony@example.com",
                            Name = "Sony",
                            PhoneNumber = "555-555-5555",
                            RegisteredOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Website = "www.sony.com"
                        });
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("nvarchar(170)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 2,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 3,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 5,
                            Name = "France"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 30,
                            Name = "United Arab Emirates"
                        });
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Canon EOS R6 Mark II",
                            PromotionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Canon RF 24-70mm f/2.8",
                            PromotionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Canon PIXMA G650",
                            PromotionId = 4
                        },
                        new
                        {
                            Id = 4,
                            Name = "Canon i-SENSYS MF655Cdw",
                            PromotionId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Canon EOS R8",
                            PromotionId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Canon PowerShot V10",
                            PromotionId = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "Canon RF 50mm f/1.8",
                            PromotionId = 6
                        },
                        new
                        {
                            Id = 8,
                            Name = "Canon SELPHY CP1500",
                            PromotionId = 13
                        },
                        new
                        {
                            Id = 9,
                            Name = "Nikon Z6 III",
                            PromotionId = 7
                        },
                        new
                        {
                            Id = 10,
                            Name = "Nikon NIKKOR Z 24-120mm",
                            PromotionId = 7
                        },
                        new
                        {
                            Id = 11,
                            Name = "Nikon COOLPIX P950",
                            PromotionId = 8
                        },
                        new
                        {
                            Id = 12,
                            Name = "Nikon Z fc",
                            PromotionId = 9
                        },
                        new
                        {
                            Id = 13,
                            Name = "Nikon Z 50mm f/1.8 S",
                            PromotionId = 14
                        },
                        new
                        {
                            Id = 14,
                            Name = "Sony WH-1000XM5",
                            PromotionId = 10
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sony WF-1000XM5",
                            PromotionId = 10
                        },
                        new
                        {
                            Id = 16,
                            Name = "Sony SRS-XB100",
                            PromotionId = 11
                        },
                        new
                        {
                            Id = 17,
                            Name = "Sony Alpha 7 IV",
                            PromotionId = 12
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sony ULT Field 1",
                            PromotionId = 15
                        });
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PromotionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Canon Summer Sale",
                            PromotionType = 0,
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            EndDate = new DateTime(2027, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nikon Winter Clearance",
                            PromotionType = 0,
                            StartDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sony Holiday Deals",
                            PromotionType = 0,
                            StartDate = new DateTime(2026, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 1,
                            EndDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Canon Back to School",
                            PromotionType = 0,
                            StartDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 1,
                            EndDate = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Canon Black Friday",
                            PromotionType = 0,
                            StartDate = new DateTime(2026, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 1,
                            EndDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Canon Spring Photo Fest",
                            PromotionType = 0,
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 2,
                            EndDate = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nikon Autumn Lens Offer",
                            PromotionType = 0,
                            StartDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 2,
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nikon Summer Adventure",
                            PromotionType = 0,
                            StartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 2,
                            EndDate = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nikon New Year Bundle",
                            PromotionType = 0,
                            StartDate = new DateTime(2026, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 3,
                            EndDate = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sony Audio Week",
                            PromotionType = 0,
                            StartDate = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            ClientId = 3,
                            EndDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sony Easter Promo",
                            PromotionType = 0,
                            StartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            ClientId = 3,
                            EndDate = new DateTime(2027, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sony Winter Cashback",
                            PromotionType = 0,
                            StartDate = new DateTime(2027, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            ClientId = 1,
                            EndDate = new DateTime(2027, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Canon Valentine's Print Deal",
                            PromotionType = 0,
                            StartDate = new DateTime(2027, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            ClientId = 2,
                            EndDate = new DateTime(2027, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nikon Spring Wildlife Promo",
                            PromotionType = 0,
                            StartDate = new DateTime(2027, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            ClientId = 3,
                            EndDate = new DateTime(2027, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sony Summer Sound Festival",
                            PromotionType = 0,
                            StartDate = new DateTime(2027, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.PromotionCountry", b =>
                {
                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("PromotionId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("PromotionsCountries");

                    b.HasData(
                        new
                        {
                            PromotionId = 1,
                            CountryId = 1
                        },
                        new
                        {
                            PromotionId = 1,
                            CountryId = 4
                        },
                        new
                        {
                            PromotionId = 1,
                            CountryId = 5
                        },
                        new
                        {
                            PromotionId = 4,
                            CountryId = 1
                        },
                        new
                        {
                            PromotionId = 4,
                            CountryId = 3
                        },
                        new
                        {
                            PromotionId = 5,
                            CountryId = 2
                        },
                        new
                        {
                            PromotionId = 5,
                            CountryId = 8
                        },
                        new
                        {
                            PromotionId = 6,
                            CountryId = 1
                        },
                        new
                        {
                            PromotionId = 7,
                            CountryId = 1
                        },
                        new
                        {
                            PromotionId = 7,
                            CountryId = 4
                        },
                        new
                        {
                            PromotionId = 7,
                            CountryId = 21
                        },
                        new
                        {
                            PromotionId = 8,
                            CountryId = 7
                        },
                        new
                        {
                            PromotionId = 8,
                            CountryId = 24
                        },
                        new
                        {
                            PromotionId = 9,
                            CountryId = 1
                        },
                        new
                        {
                            PromotionId = 9,
                            CountryId = 2
                        },
                        new
                        {
                            PromotionId = 9,
                            CountryId = 3
                        },
                        new
                        {
                            PromotionId = 9,
                            CountryId = 4
                        },
                        new
                        {
                            PromotionId = 10,
                            CountryId = 20
                        },
                        new
                        {
                            PromotionId = 11,
                            CountryId = 6
                        },
                        new
                        {
                            PromotionId = 11,
                            CountryId = 17
                        },
                        new
                        {
                            PromotionId = 12,
                            CountryId = 1
                        },
                        new
                        {
                            PromotionId = 12,
                            CountryId = 4
                        },
                        new
                        {
                            PromotionId = 12,
                            CountryId = 5
                        },
                        new
                        {
                            PromotionId = 12,
                            CountryId = 6
                        },
                        new
                        {
                            PromotionId = 12,
                            CountryId = 7
                        },
                        new
                        {
                            PromotionId = 13,
                            CountryId = 1
                        },
                        new
                        {
                            PromotionId = 14,
                            CountryId = 16
                        },
                        new
                        {
                            PromotionId = 14,
                            CountryId = 22
                        },
                        new
                        {
                            PromotionId = 14,
                            CountryId = 26
                        },
                        new
                        {
                            PromotionId = 15,
                            CountryId = 2
                        },
                        new
                        {
                            PromotionId = 15,
                            CountryId = 9
                        });
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("UserId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Client", b =>
                {
                    b.HasOne("PromotionsCRM.Data.Models.Country", "Country")
                        .WithMany("Clients")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Customer", b =>
                {
                    b.HasOne("PromotionsCRM.Data.Models.Country", "Country")
                        .WithMany("Customers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Product", b =>
                {
                    b.HasOne("PromotionsCRM.Data.Models.Promotion", "Promotion")
                        .WithMany("Products")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Promotion", b =>
                {
                    b.HasOne("PromotionsCRM.Data.Models.Client", "Client")
                        .WithMany("Promotions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.PromotionCountry", b =>
                {
                    b.HasOne("PromotionsCRM.Data.Models.Country", "Country")
                        .WithMany("PromotionsCountries")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PromotionsCRM.Data.Models.Promotion", "Promotion")
                        .WithMany("PromotionsCountries")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Submission", b =>
                {
                    b.HasOne("PromotionsCRM.Data.Models.Customer", "Customer")
                        .WithMany("Submissions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PromotionsCRM.Data.Models.Product", "Product")
                        .WithMany("Submissions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PromotionsCRM.Data.Models.Promotion", "Promotion")
                        .WithMany("Submissions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PromotionsCRM.Data.Models.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId");

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Promotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Client", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Country", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Customers");

                    b.Navigation("PromotionsCountries");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Customer", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Product", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Promotion", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("PromotionsCountries");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.User", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
