// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromotionsCRM.Data;

#nullable disable

namespace PromotionsCRM.Migrations
{
    [DbContext(typeof(PromotionsCrmDbContext))]
    partial class PromotionsCrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PromotionsCRM.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("nvarchar(170)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 2,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 3,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 5,
                            Name = "France"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 30,
                            Name = "United Arab Emirates"
                        });
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.PromotionCountry", b =>
                {
                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("PromotionId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("PromotionsCountries");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("UserId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Client", b =>
                {
                    b.HasOne("PromotionsCRM.Data.Models.Country", "Country")
                        .WithMany("Clients")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Customer", b =>
                {
                    b.HasOne("PromotionsCRM.Data.Models.Country", "Country")
                        .WithMany("Customers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Product", b =>
                {
                    b.HasOne("PromotionsCRM.Data.Models.Promotion", "Promotion")
                        .WithMany("Products")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Promotion", b =>
                {
                    b.HasOne("PromotionsCRM.Data.Models.Client", "Client")
                        .WithMany("Promotions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.PromotionCountry", b =>
                {
                    b.HasOne("PromotionsCRM.Data.Models.Country", "Country")
                        .WithMany("PromotionsCountries")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PromotionsCRM.Data.Models.Promotion", "Promotion")
                        .WithMany("PromotionsCountries")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Submission", b =>
                {
                    b.HasOne("PromotionsCRM.Data.Models.Customer", "Customer")
                        .WithMany("Submissions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PromotionsCRM.Data.Models.Product", "Product")
                        .WithMany("Submissions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PromotionsCRM.Data.Models.Promotion", "Promotion")
                        .WithMany("Submissions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PromotionsCRM.Data.Models.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId");

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Promotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Client", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Country", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Customers");

                    b.Navigation("PromotionsCountries");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Customer", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Product", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.Promotion", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("PromotionsCountries");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("PromotionsCRM.Data.Models.User", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
